FROM archlinux:latest

RUN pacman -Sy; pacman --noconfirm -S git expect 

# some distros do not seem to like github certs
RUN git config --global http.sslVerify false ;\
    git clone https://github.com/boddenberg-it/.githooker.git ;\
    mkdir .githooker/githooks ;\
    cd .githooker ;\
    ./run_tests.sh
