#!/usr/bin/expect -f

set timeout 1

set answer [lindex $argv 0];
set script [lindex $argv 1];

spawn $script/githooker.sh interactive

expect -re "32mpre-push hook is enabled*.*disable*.*"
send -- "$answer\r"

expect -re "33mpre-rebase hook is disabled*.*enable*.*"
send -- "$answer\r"
 
expect -re "31mpre-commit hook is orphaned*.*delete*.*"
send -- "$answer\r"

expect -re "33mpre-commit hook deleted*.*"
