FROM alpine:latest

RUN apk update && apk upgrade && \
    apk add --no-cache bash git expect

# some distros do not seem to like github certs
RUN git config --global http.sslVerify false ;\
    git config --global user.email "githooker@boddenberg.it" ;\
    git config --global user.name "githooker" ;\
    git clone https://github.com/boddenberg-it/.githooker.git ;\
    cd .githooker ;\
    ./tests/run_tests.sh
