FROM alpine:latest

RUN apk update && apk upgrade && apk add --no-cache bash git expect

COPY ./tests/_docker/run_githooker_testsuites.sh run_githooker_testsuites.sh

RUN ./run_githooker_testsuites.sh
