FROM debian:latest

RUN apt-get update; apt-get --no-install-recommends install -y git expect

COPY ./tests/_docker/run_githooker_testsuites.sh run_githooker_testsuites.sh

RUN ./run_githooker_testsuites.sh
